name: "PufferPanel"
version: "3.0.9-HA1.1.1"
slug: "pufferpanel"
description: "Panneau de gestion de serveurs de jeux (Minecraft et autres)"
url: "https://pufferpanel.com"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
docker_api: true
ports:
  8080/tcp: 8080
  5657/tcp: 5657
ports_description:
  8080/tcp: "Interface web PufferPanel"
  5657/tcp: "SFTP pour les serveurs de jeux"
map:
  - addon_config:rw
  - share:rw
  - data:rw
options:
  create_user: false
  username: "admin"
  email: "admin@example.com"
  password: ""
  is_admin: true
schema:
  create_user: bool
  username: str
  email: email
  password: password
  is_admin: bool
